name = "youtube-thumbnail-downloader"
main = "src/index.js"
compatibility_date = "2026-08-07"
workers_dev = true

routes = [
  { pattern = "yt-thumbnail-downloader.site/*", zone_name = "yt-thumbnail-downloader.site" },
  { pattern = "www.yt-thumbnail-downloader.site/*", zone_name = "yt-thumbnail-downloader.site" },
]

[assets]
directory = "public"
run_worker_first = true
binding = "ASSETS"
