export const SITE = {
  domain: "https://youtube-thumbnail-downloader.aziizboukerma.workers.dev",
  name: "YouTube Thumbnail Downloader",
  toolName: "YouTube Thumbnail Downloader",
};

export const LANGUAGES = [
  { code: "en", name: "English" },
  { code: "de", name: "Deutsch" },
  { code: "es", name: "Español" },
  { code: "fr", name: "Français" },
  { code: "it", name: "Italiano" },
  { code: "pt", name: "Português" },
  { code: "nl", name: "Nederlands" },
  { code: "pl", name: "Polski" },
  { code: "sv", name: "Svenska" },
  { code: "da", name: "Dansk" },
  { code: "no", name: "Norsk" },
  { code: "fi", name: "Suomi" },
  { code: "cs", name: "Čeština" },
  { code: "el", name: "Ελληνικά" },
  { code: "ro", name: "Română" },
  { code: "hu", name: "Magyar" },
  { code: "tr", name: "Türkçe" },
  { code: "ru", name: "Русский" },
  { code: "uk", name: "Українська" },
  { code: "ar", name: "العربية" },
  { code: "he", name: "עברית" },
  { code: "fa", name: "فارسی" },
  { code: "hi", name: "हिन्दी" },
  { code: "bn", name: "বাংলা" },
  { code: "ur", name: "اردو" },
  { code: "ja", name: "日本語" },
  { code: "ko", name: "한국어" },
  { code: "zh-CN", name: "简体中文" },
  { code: "zh-TW", name: "繁體中文" },
  { code: "vi", name: "Tiếng Việt" },
  { code: "th", name: "ไทย" },
  { code: "id", name: "Bahasa Indonesia" },
  { code: "ms", name: "Bahasa Melayu" },
  { code: "tl", name: "Tagalog" },
];

export const PSEO = [
  {
    slug: "youtube-thumbnail-downloader",
    primary: "youtube thumbnail downloader",
    title: "YouTube Thumbnail Downloader — Download Video Thumbnails in HD",
    meta: "Download YouTube thumbnails in HD, SD and HQ from any video link. Paste the URL, pick a resolution, and save the image — free, no sign-up, no watermark.",
    h1: "YouTube Thumbnail Downloader",
    intro: [
      "A YouTube thumbnail downloader grabs the preview image of any video straight from YouTube's public image CDN. You only need the video link — the video ID is extracted automatically and every available resolution is shown in a grid.",
      "Everything runs in your browser. There is no sign-up, no watermark, and no limit on how many thumbnails you can download.",
    ],
    steps: [
      "Paste a YouTube link — watch, shorts, embed, or youtu.be all work.",
      "Click Get Thumbnails and wait a moment while the sizes load.",
      "Preview the video and the highest-quality thumbnail at the top.",
      "Click Download on any size to save it to your device.",
    ],
    faq: [
      ["Is the YouTube thumbnail downloader free?", "Yes — it is completely free, requires no sign-up, and lets you download unlimited thumbnails."],
      ["Which sizes can I download?", "Most videos offer five sizes: 1280x720 HD, 640x480 SD, 480x360 HQ, 320x180 and 120x90. The HD version is only available for videos that have one."],
      ["Does it add a watermark?", "No — thumbnails are saved exactly as they appear on YouTube, without any watermark."],
    ],
  },
  {
    slug: "download-youtube-thumbnails",
    primary: "download youtube thumbnails",
    title: "Download YouTube Thumbnails Online — All Sizes in One Click",
    meta: "Download YouTube thumbnails online in all sizes. Paste the video link and save the HD, SD or HQ thumbnail instantly. Free tool, no install, no sign-up.",
    h1: "Download YouTube Thumbnails Online",
    intro: [
      "Downloading a YouTube thumbnail is just a link away. This tool lists every thumbnail size YouTube provides for a video and lets you save each one with a single click.",
      "Use it for your own videos, design mockups, or as a quick reference — the image is saved to your device instantly.",
    ],
    steps: [
      "Copy the link of any YouTube video.",
      "Paste it into the box and press Enter.",
      "Choose the resolution you need from the list.",
      "Click Download to save the image file.",
    ],
    faq: [
      ["Do I need to install an extension?", "No — this works directly in your browser with nothing to install."],
      ["Can I download thumbnails from private videos?", "No — only public videos with publicly accessible thumbnails can be downloaded."],
      ["Is it free?", "Yes, free and unlimited, with no account required."],
    ],
  },
  {
    slug: "youtube-thumbnail-grabber",
    primary: "youtube thumbnail grabber",
    title: "YouTube Thumbnail Grabber — Grab Any Video Thumbnail",
    meta: "Grab the thumbnail of any YouTube video in seconds. Paste the link, preview every size, and save the one you want. Free online thumbnail grabber.",
    h1: "YouTube Thumbnail Grabber",
    intro: [
      "The YouTube thumbnail grabber pulls the preview image of any video so you can preview it at every resolution and save the best one. No more digging through page source or guessing the image URL.",
      "It handles watch links, shorts, embeds, and youtu.be short links automatically.",
    ],
    steps: [
      "Paste the video link into the grabber.",
      "Press Enter or click Get Thumbnails.",
      "Browse the HD, SD, and HQ previews.",
      "Grab the size you want with one click.",
    ],
    faq: [
      ["What does a thumbnail grabber do?", "It retrieves every thumbnail image YouTube generated for a video and lets you download them."],
      ["Does it work for YouTube Shorts?", "Yes — Shorts links are supported and their thumbnails are extracted the same way."],
      ["Is my link stored anywhere?", "No. The link is only used to fetch the public thumbnail image from YouTube's CDN."],
    ],
  },
  {
    slug: "youtube-thumbnail-extractor",
    primary: "youtube video thumbnail extractor",
    title: "YouTube Thumbnail Extractor — Extract Video Thumbnails Instantly",
    meta: "Extract the thumbnail image from any YouTube video instantly. Paste the link and get every available resolution. Free, private, no sign-up.",
    h1: "YouTube Thumbnail Extractor",
    intro: [
      "An extractor pulls the thumbnail image files out of a YouTube video automatically. Instead of using screenshot tools or inspecting the page source, paste the link and the images are extracted for you.",
      "Every resolution YouTube offers is returned at once, from the tiny default to the full HD 1280x720 image.",
    ],
    steps: [
      "Paste the YouTube video URL.",
      "The tool extracts the video ID automatically.",
      "All thumbnail sizes are displayed as previews.",
      "Save the resolution you need as a JPG file.",
    ],
    faq: [
      ["What is a YouTube thumbnail extractor?", "A tool that fetches the public thumbnail images of a video from YouTube's image server and lets you download them."],
      ["Do I need the video ID?", "No — the ID is extracted from the link for you."],
      ["Are the images original quality?", "Yes, each size is saved at the exact resolution YouTube publishes it."],
    ],
  },
  {
    slug: "youtube-thumbnail-saver",
    primary: "save youtube video thumbnail",
    title: "Save YouTube Video Thumbnail — Download & Keep It Forever",
    meta: "Save the thumbnail of any YouTube video to your computer. Choose the resolution and keep the image forever. Free online thumbnail saver.",
    h1: "Save YouTube Video Thumbnail",
    intro: [
      "Right-clicking and saving from YouTube rarely works because the thumbnail is a dynamic element. This tool saves the actual image file so you can keep it forever, in whatever resolution you choose.",
      "Perfect for storing thumbnails of your own uploads or archiving reference designs.",
    ],
    steps: [
      "Paste the video link.",
      "Pick your preferred resolution.",
      "Click Download to save the JPG.",
      "Keep it as long as you need.",
    ],
    faq: [
      ["Can I save the HD thumbnail?", "Yes — if the video has an HD thumbnail (1280x720), it is available in the list."],
      ["What format is the file?", "Thumbnails are saved as JPG files."],
      ["Does it work on mobile?", "Yes, the tool works on any device with a browser."],
    ],
  },
  {
    slug: "hd-youtube-thumbnail-downloader",
    primary: "hd youtube thumbnail downloader",
    title: "HD YouTube Thumbnail Downloader — Download 1280x720 Thumbnails",
    meta: "Download HD YouTube thumbnails (1280x720) from any video link. Get the highest quality preview image instantly. Free HD thumbnail downloader.",
    h1: "HD YouTube Thumbnail Downloader",
    intro: [
      "The HD YouTube thumbnail is a 1280x720 image that YouTube stores as maxresdefault. Not every video has one — it depends on the uploader — but when it does, this tool makes it one click away.",
      "If HD is unavailable, the tool automatically falls back to the sharpest available size, so you always get the best possible image.",
    ],
    steps: [
      "Paste the video link.",
      "Look for the HD card in the thumbnail list.",
      "If it exists, click Download to save 1280x720.",
      "Otherwise grab the SD or HQ version.",
    ],
    faq: [
      ["Why don't some videos have an HD thumbnail?", "The 1280x720 maxresdefault image is only generated when the uploader enables high-quality thumbnails."],
      ["What resolution is the HD thumbnail?", "1280x720 pixels, the largest thumbnail YouTube offers."],
      ["Is there a 4K thumbnail?", "No — 1280x720 is the maximum thumbnail size YouTube publishes."],
    ],
  },
  {
    slug: "download-maxresdefault-thumbnail",
    primary: "download maxresdefault thumbnail",
    title: "Download maxresdefault Thumbnail — The 1280x720 HD Image",
    meta: "Download the maxresdefault thumbnail (1280x720 HD) of any YouTube video. Get the full-quality preview image directly from YouTube's CDN.",
    h1: "Download maxresdefault Thumbnail",
    intro: [
      "maxresdefault.jpg is the highest-resolution thumbnail YouTube stores — 1280x720 pixels. This tool fetches it straight from YouTube's image CDN and lets you save it as a file.",
      "When a video has no maxresdefault image, the tool checks the other sizes so you are never left empty-handed.",
    ],
    steps: [
      "Paste the YouTube link.",
      "The tool checks for maxresdefault automatically.",
      "Download the HD image if it exists.",
      "Use the fallback sizes if it does not.",
    ],
    faq: [
      ["What is maxresdefault?", "The filename YouTube uses for the largest thumbnail, 1280x720 HD."],
      ["Where does the image come from?", "It is fetched from YouTube's public image server (i.ytimg.com)."],
      ["Can I get it without a tool?", "Yes, but the URL must be built manually — this tool does it for you."],
    ],
  },
  {
    slug: "youtube-shorts-thumbnail-downloader",
    primary: "youtube shorts thumbnail downloader",
    title: "YouTube Shorts Thumbnail Downloader — Save Shorts Thumbnails",
    meta: "Download thumbnails from YouTube Shorts videos. Paste the Shorts link and save the HD or SD preview image instantly. Free and easy.",
    h1: "YouTube Shorts Thumbnail Downloader",
    intro: [
      "YouTube Shorts have thumbnails too, and they can be downloaded just like regular videos. Paste a Shorts link and every available thumbnail size is fetched for you.",
      "The tool recognizes the /shorts/ URL format automatically, so you do not need to extract the video ID by hand.",
    ],
    steps: [
      "Copy the link of the Shorts video.",
      "Paste it into the box and press Enter.",
      "Preview the available thumbnail sizes.",
      "Download the resolution you want.",
    ],
    faq: [
      ["Can I download a Shorts thumbnail in HD?", "Yes, if the Shorts video has an HD thumbnail it appears in the list."],
      ["Do I need the short video ID?", "No — the /shorts/ link contains it and the tool reads it automatically."],
      ["Is it free?", "Yes, free and unlimited."],
    ],
  },
  {
    slug: "thumbnail-from-video-id",
    primary: "get youtube thumbnail from video id",
    title: "Get YouTube Thumbnail from Video ID — Paste the ID Directly",
    meta: "Get the thumbnail of any YouTube video from its 11-character video ID. Paste the ID and download every available size instantly. Free tool.",
    h1: "Get YouTube Thumbnail from Video ID",
    intro: [
      "Every YouTube video has a unique 11-character ID. If you already have the ID — from an embed, an API, or a playlist — you can paste it directly without a full URL.",
      "The tool builds the thumbnail URLs for you and shows every size that exists.",
    ],
    steps: [
      "Copy the 11-character video ID.",
      "Paste it into the box.",
      "Press Enter to load the thumbnails.",
      "Download the size you need.",
    ],
    faq: [
      ["Where is the video ID in a URL?", "After v= in watch links (youtube.com/watch?v=VIDEO_ID), or after the slash in youtu.be/VIDEO_ID links."],
      ["Can I paste just the ID?", "Yes — a bare 11-character ID is accepted."],
      ["Is the ID ever uploaded?", "No, it is only used to build the public thumbnail URL in your browser."],
    ],
  },
  {
    slug: "youtube-thumbnail-viewer",
    primary: "view youtube video thumbnail",
    title: "View YouTube Video Thumbnails — See All Sizes Side by Side",
    meta: "View the thumbnail of any YouTube video at every size, side by side. Paste the link and compare HD, SD and HQ previews instantly. Free viewer.",
    h1: "View YouTube Video Thumbnails",
    intro: [
      "Sometimes you just want to look at a thumbnail at full resolution — for a design, a mood board, or your own uploads. This viewer shows every size YouTube has for a video side by side.",
      "Click any preview to open the full image in a new tab, or download it directly.",
    ],
    steps: [
      "Paste a YouTube link.",
      "All thumbnail sizes appear in a grid.",
      "Click an image to view it full size.",
      "Download the one you like.",
    ],
    faq: [
      ["Can I compare all sizes at once?", "Yes — every size is displayed in a single grid."],
      ["Does it work with any video?", "Yes, any public YouTube video, including Shorts and live streams."],
      ["Is the viewer free?", "Yes, completely free."],
    ],
  },
  {
    slug: "copy-youtube-thumbnail-url",
    primary: "copy youtube thumbnail url",
    title: "Copy YouTube Thumbnail URL — Get the Direct Image Link",
    meta: "Copy the direct URL of any YouTube video thumbnail. Paste the video link and get the i.ytimg.com image URL for every size. Free tool.",
    h1: "Copy YouTube Thumbnail URL",
    intro: [
      "Need the direct image URL of a video thumbnail for embedding or sharing? This tool shows the exact i.ytimg.com URL for every size YouTube offers.",
      "Each URL points to a plain JPG on YouTube's public image CDN, ready to embed anywhere.",
    ],
    steps: [
      "Paste the video link.",
      "View the direct URL for every size.",
      "Open a thumbnail in a new tab.",
      "Copy the URL from the address bar.",
    ],
    faq: [
      ["What is the thumbnail URL format?", "It follows the pattern https://i.ytimg.com/vi/VIDEO_ID/SIZE.jpg, where SIZE is maxresdefault, sddefault, hqdefault, mqdefault or default."],
      ["Can I embed the image anywhere?", "Yes, the URL is a plain JPG that can be embedded in most platforms."],
      ["Is this free?", "Yes."],
    ],
  },
  {
    slug: "youtube-thumbnail-downloader-without-extension",
    primary: "youtube thumbnail downloader without extension",
    title: "YouTube Thumbnail Downloader Without Extension — No Install",
    meta: "Download YouTube thumbnails without installing any browser extension. A pure web app that works in any browser. Free, private, no add-ons.",
    h1: "YouTube Thumbnail Downloader Without Extension",
    intro: [
      "Browser extensions for downloading thumbnails can slow down your browser and request broad permissions. This tool needs nothing — it is a normal web page that works in any modern browser.",
      "Open it, paste a link, and download. No installation, no permissions, no add-ons.",
    ],
    steps: [
      "Open this page in your browser.",
      "Paste the YouTube video link.",
      "Pick a resolution.",
      "Click Download — done.",
    ],
    faq: [
      ["Do I need to install anything?", "No, the tool runs entirely in your browser."],
      ["Is it safer than an extension?", "It has no permissions and no code that touches your browser, so there is less to go wrong."],
      ["Which browsers are supported?", "Any modern browser — Chrome, Firefox, Safari, Edge, and mobile browsers."],
    ],
  },
  {
    slug: "download-thumbnail-from-youtube-link",
    primary: "download thumbnail from youtube link",
    title: "Download Thumbnail from YouTube Link — One Paste, Instant Save",
    meta: "Download the thumbnail from any YouTube link in one click. Paste the video URL, choose a size, and save the image. Free, no sign-up, no watermark.",
    h1: "Download Thumbnail from YouTube Link",
    intro: [
      "Turn any YouTube link into a downloadable image. Paste the URL, and within seconds the tool lists every thumbnail resolution for that video, ready to save.",
      "There is no account, no watermark, and no limit — paste as many links as you like.",
    ],
    steps: [
      "Copy the YouTube link you want.",
      "Paste it into the box.",
      "Choose the resolution you prefer.",
      "Download the thumbnail file.",
    ],
    faq: [
      ["Do I need an account?", "No, the tool is completely open."],
      ["How fast does it work?", "Thumbnails usually load within a second or two."],
      ["Can I download several sizes?", "Yes, each size has its own Download button."],
    ],
  },
  {
    slug: "youtube-thumbnail-sizes",
    primary: "youtube thumbnail sizes",
    title: "YouTube Thumbnail Sizes — Resolution Guide & Downloader",
    meta: "All YouTube thumbnail sizes explained: 1280x720 HD, 640x480 SD, 480x360, 320x180 and 120x90. Plus a free downloader for every size.",
    h1: "YouTube Thumbnail Sizes",
    intro: [
      "YouTube generates five thumbnail sizes for every video: maxresdefault (1280x720 HD), sddefault (640x480), hqdefault (480x360), mqdefault (320x180), and default (120x90). The HD size is only present when the uploader enabled high-quality thumbnails.",
      "Paste a link below to see which sizes exist for a specific video and download any of them.",
    ],
    steps: [
      "Paste a video link to check its sizes.",
      "Compare each resolution side by side.",
      "Download the size you need.",
    ],
    faq: [
      ["What is the recommended thumbnail size for uploads?", "YouTube recommends 1280x720, at least 640 pixels wide, saved as JPG, PNG, or GIF."],
      ["Which size is best for sharing?", "The 1280x720 HD image is the sharpest, but 640x480 is a good lightweight alternative."],
      ["Do all videos have every size?", "No — the HD maxresdefault size is missing on videos that were not given a high-quality thumbnail."],
    ],
  },
  {
    slug: "download-video-cover-image",
    primary: "download video cover image from youtube",
    title: "Download YouTube Video Cover Image — Get the Channel Thumbnail",
    meta: "Download the cover image (thumbnail) of any YouTube video. Paste the link and save the HD cover image instantly. Free online cover downloader.",
    h1: "Download YouTube Video Cover Image",
    intro: [
      "The cover image of a video is its thumbnail — the first impression viewers see. This tool fetches it at the highest available resolution and lets you save it as a JPG file.",
      "Great for creators who want their own cover images back, or for design references.",
    ],
    steps: [
      "Paste the video link.",
      "The cover image loads at the highest size.",
      "Download the HD version or pick another.",
      "Save the image to your device.",
    ],
    faq: [
      ["What is the video cover image?", "It is the thumbnail, the preview image shown in search results and the player."],
      ["Can I download it in HD?", "Yes, if the video has an HD thumbnail."],
      ["Is it free to use?", "The tool is free. Remember thumbnails are the uploader's property, so check usage rights if you plan to reuse them."],
    ],
  },
  {
    slug: "free-youtube-thumbnail-downloader",
    primary: "free youtube thumbnail downloader",
    title: "Free YouTube Thumbnail Downloader — No Sign-Up, No Limits",
    meta: "Free YouTube thumbnail downloader with no sign-up and no limits. Paste any video link and download HD thumbnails instantly. 100% private.",
    h1: "Free YouTube Thumbnail Downloader",
    intro: [
      "This is a free YouTube thumbnail downloader: no account, no payment, no usage caps. Paste any public video link and download its thumbnail at any available resolution.",
      "Everything happens in your browser, so there are no servers storing your links and no privacy worries.",
    ],
    steps: [
      "Paste the video link.",
      "Browse the available resolutions.",
      "Click Download to save the image.",
      "Repeat as many times as you need.",
    ],
    faq: [
      ["Is it really free?", "Yes — completely free, with no sign-up and no limits."],
      ["Is my data private?", "Yes — links are processed in your browser and nothing is stored."],
      ["Can I download as many as I want?", "Yes, there is no limit."],
    ],
  },
];
